{% set name = "sagemaker-jupyterlab-extension-common" %}
{% set version = "0.1.36" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.org/packages/source/{{ name[0] }}/{{ name }}/{{ name.replace('-', '_') }}-{{ version }}.tar.gz
  sha256: a7f235cfcf2fc72e9064cfcb6d36b2f4178f84347de53302e4f0917d413e1ebd

build:
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv
  number: 0

requirements:
  host:
    - python {{ python_min }}
    - jupyter_packaging >=0.12.0,<0.13.dev0
    - setuptools >=40.8.0
    - wheel
    - urllib3 <2
    - jupyterlab >4
    - pip
  run:
    - python >={{ python_min }}
    - jupyterlab >=4
    - jupyter_events >=0.6.0
    - aiobotocore >=2.7.0
    - aws-embedded-metrics
    - y-py >=0.6.0,<0.7.0
    - ypy-websocket >=0.12.0
    - nbformat >=5.9.2
    - pydantic >=1.10.17,<3

test:
  imports:
    - sagemaker_jupyterlab_extension_common
  commands:
    - pip check
  requires:
    - pip
    - python {{ python_min }}

about:
  home: https://aws.amazon.com/sagemaker/
  summary: SageMaker JupyterLab workspace common module
  license: LicenseRef-.amazon.com.-AmznSL-1.0
  license_file: LICENSE

extra:
  recipe-maintainers:
    - gogakoreli
    - chaonengquan
    - bhadrip
    - zuoyuanh
